# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
