# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='restapi.ProfileImage'),
        ),
        migrations.AddField(
            model_name='profileimagelist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restapi.Profile'),
        ),
    ]
